version: '3.8'

services:
  shaka-bot:
    build: .
    container_name: shaka-bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - shaka-network

networks:
  shaka-network:
    driver: bridge
